### PR TITLE
Split names into forename and surname

### PR DESCRIPTION
**Pull request by lclarksl**

### CODE REVIEW

**Comment by ianlovell** [comment]
:shipit:

**Comment by csscottlogic** [comment]
Why do we want to do this? Names can be more complex than just Bob Jones, e.g. William J. Brown III. Would a single string not be better unless a requirement comes up to split the name into components?

**Comment by lclarksl** [comment]
It will let us sort by last name on the front end

**Comment by dwybourn** [comment]
This is a bit of an edge case, but what if they don’t have a last name? Like in Iceland

**Comment by ianlovell** [comment]
Only name we have so far is Lukasz (Luke) Kreczko - which would still work if the last name is the last word. Don't we currently store the data as forename/surname?

**Comment by ianlovell** [comment]
Also Bjork would still work, as she just wouldn't have a surname. Does she still work?

**Comment by lclarksl** [comment]
Yes. You’d do sorting by last and then first name anyway, in case of identical surnames

**Comment by dwybourn** [comment]
:shipit:

**Pull request merged**
